pipeline {
  agent any

  parameters {
    string(defaultValue: "", description: "Deployment Name?", name: "deploymentName")
    choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "What AZ?", name: "azDeploy")
    booleanParam(defaultValue: false, description: "CONFIRM DEPLOYMENT?", name: "confirmDeploy")
  }

  stages {
    stage("Deploy") {
      steps {
        echo "String set to ${params.deploymentName} \n"
        echo "Choice set to ${params.azDeploy} \n"
        echo "Boolean set to ${params.confirmDeploy} \n"
      }
    }
  }
}